site_name: Openveo Plugin Generator
repo_url: https://github.com/veo-labs/openveo-plugin-generator
theme: readthedocs
site_dir: site/version
markdown_extensions:
  - fenced_code
  - tables
pages:
- 'INTRODUCTION': 'index.md'
- 'DEVELOPERS':
  - 'Installation': 'developers/installation.md'
  - 'Generators': 'developers/generators.md'
  - 'conf.js': 'developers/conf.md'
  - 'Back end AngularJS': 'developers/back-end.md'
  - 'Write a plugin': 'developers/write-plugin.md'
  - 'CSS / SASS / JS compilation': 'developers/compilation.md'
  - 'Template engine': 'developers/template-engine.md'
  - 'Logger': 'developers/logger.md'
  - 'I18N and I10N': 'developers/i18n.md'
  - 'Coding standards': 'developers/coding-standards.md'
  - 'Unit tests': 'developers/unit-tests.md'
  - 'End to end tests': 'developers/end-to-end-tests.md'
- 'API': 'api.md'